// src/components/apps/Blue-Video-App/src/Controls.tsx
import React from 'react';
import {
    Play, Pause, SkipBack, SkipForward, Volume2, VolumeX,
    Maximize2, Settings, List, FolderOpen,
} from 'lucide-react';

interface Props {
    playing: boolean;
    current: number;
    duration: number;
    volume: number;
    muted: boolean;
    speed: number;
    fullscreen: boolean;
    showPlaylist: boolean;
    showSettings: boolean;
    onPlay: () => void;
    onPrev: () => void;
    onNext: () => void;
    onSeek: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onVolume: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onMute: () => void;
    onFullscreen: () => void;
    onTogglePlaylist: () => void;
    onToggleSettings: () => void;
    onOpenFiles: () => void;
}

function fmtTime(s: number) {
    const m = Math.floor(s / 60); const sec = Math.floor(s % 60);
    return `${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
}

const Controls: React.FC<Props> = ({
    playing, current, duration, volume, muted, speed, fullscreen,
    showPlaylist, showSettings,
    onPlay, onPrev, onNext, onSeek, onVolume, onMute, onFullscreen,
    onTogglePlaylist, onToggleSettings, onOpenFiles,
}) => (
    <div className="bg-slate-900/95 border-t border-white/5 p-2 shrink-0">
        <input type="range" min={0} max={duration || 1} value={current} step={0.1} onChange={onSeek}
            className="w-full h-1 mb-2 accent-blue-500 cursor-pointer" />
        <div className="flex items-center gap-2">
            <button onClick={onPrev}     className="p-1.5 hover:bg-white/10 rounded"><SkipBack    size={16}/></button>
            <button onClick={onPlay}     className="p-2    hover:bg-white/10 rounded">{playing ? <Pause size={18}/> : <Play size={18}/>}</button>
            <button onClick={onNext}     className="p-1.5 hover:bg-white/10 rounded"><SkipForward size={16}/></button>
            <span className="text-xs text-slate-400 font-mono mx-1">{fmtTime(current)} / {fmtTime(duration)}</span>
            <div className="flex-1" />
            <button onClick={onMute}     className="p-1.5 hover:bg-white/10 rounded">{muted ? <VolumeX size={15}/> : <Volume2 size={15}/>}</button>
            <input type="range" min={0} max={1} step={0.05} value={muted ? 0 : volume} onChange={onVolume}
                className="w-20 accent-blue-500 cursor-pointer" />
            <span className="text-xs text-slate-500">{speed}x</span>
            <button onClick={onOpenFiles}      className="p-1.5 hover:bg-white/10 rounded"><FolderOpen  size={15}/></button>
            <button onClick={onTogglePlaylist} className={`p-1.5 rounded ${showPlaylist ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}`}><List       size={15}/></button>
            <button onClick={onToggleSettings} className={`p-1.5 rounded ${showSettings ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}`}><Settings   size={15}/></button>
            <button onClick={onFullscreen}     className="p-1.5 hover:bg-white/10 rounded"><Maximize2   size={15}/></button>
        </div>
    </div>
);

export default Controls;

// src/lib/components/apps/Blue-Video/Controls.svelte
<script lang="ts">
  import { Play, Pause, SkipBack, SkipForward, Volume2, VolumeX, Maximize2, Settings, List, FolderOpen, PictureInPicture2 } from 'lucide-svelte';
  import { createEventDispatcher } from 'svelte';

  export let playing: boolean;
  export let current: number;
  export let duration: number;
  export let volume: number;
  export let muted: boolean;
  export let speed: number;
  export let showPlaylist: boolean;
  export let showSettings: boolean;
  export let canPiP = false;

  const dispatch = createEventDispatcher<{
    play: void; prev: void; next: void; seek: number; volume: number; mute: void;
    fullscreen: void; togglePlaylist: void; toggleSettings: void; openFiles: void; pip: void;
  }>();

  function fmtTime(s: number) {
    const m = Math.floor(s / 60), sec = Math.floor(s % 60);
    return `${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`;
  }
</script>

<div class="bg-slate-900/95 border-t border-white/5 p-2 shrink-0">
  <input type="range" min="0" max={duration || 1} value={current} step="0.1"
    on:input={(e) => dispatch('seek', parseFloat(e.currentTarget.value))}
    class="w-full h-1 mb-2 accent-blue-500 cursor-pointer" />
  <div class="flex items-center gap-2">
    <button on:click={() => dispatch('prev')} class="p-1.5 hover:bg-white/10 rounded"><SkipBack size={16} /></button>
    <button on:click={() => dispatch('play')} class="p-2 hover:bg-white/10 rounded">
      {#if playing}<Pause size={18} />{:else}<Play size={18} />{/if}
    </button>
    <button on:click={() => dispatch('next')} class="p-1.5 hover:bg-white/10 rounded"><SkipForward size={16} /></button>
    <span class="text-xs text-slate-400 font-mono mx-1">{fmtTime(current)} / {fmtTime(duration)}</span>
    <div class="flex-1" />
    <button on:click={() => dispatch('mute')} class="p-1.5 hover:bg-white/10 rounded">
      {#if muted}<VolumeX size={15} />{:else}<Volume2 size={15} />{/if}
    </button>
    <input type="range" min="0" max="1" step="0.05" value={muted ? 0 : volume}
      on:input={(e) => dispatch('volume', parseFloat(e.currentTarget.value))}
      class="w-20 accent-blue-500 cursor-pointer" />
    <span class="text-xs text-slate-500">{speed}x</span>
    <button on:click={() => dispatch('openFiles')} class="p-1.5 hover:bg-white/10 rounded"><FolderOpen size={15} /></button>
    {#if canPiP}
      <button on:click={() => dispatch('pip')} class="p-1.5 hover:bg-white/10 rounded" title="Picture-in-Picture — floats outside this window, even over other apps"><PictureInPicture2 size={15} /></button>
    {/if}
    <button on:click={() => dispatch('togglePlaylist')} class="p-1.5 rounded {showPlaylist ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}"><List size={15} /></button>
    <button on:click={() => dispatch('toggleSettings')} class="p-1.5 rounded {showSettings ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}"><Settings size={15} /></button>
    <button on:click={() => dispatch('fullscreen')} class="p-1.5 hover:bg-white/10 rounded"><Maximize2 size={15} /></button>
  </div>
</div>
