// src/lib/components/apps/Blue-Images-App/BlueImagesApp.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import {
    FolderOpen, ZoomIn, ZoomOut, Maximize2, Minimize2,
    RotateCcw, RotateCw, FlipHorizontal, FlipVertical,
    ChevronLeft, ChevronRight, Download, Crop,
    Sliders, X, RefreshCw, Image as ImageIcon,
  } from 'lucide-svelte';
  import { SystemBridge } from '../../../utils/systemBridge';

  interface ImageItem { path: string; name: string; url: string; }

  interface Adjustments {
    brightness: number; contrast: number; saturation: number; hue: number;
    blur: number; sepia: number; grayscale: number; opacity: number;
  }

  const DEFAULT_ADJ: Adjustments = { brightness: 100, contrast: 100, saturation: 100, hue: 0, blur: 0, sepia: 0, grayscale: 0, opacity: 100 };

  function adjToFilter(a: Adjustments): string {
    return [
      `brightness(${a.brightness}%)`, `contrast(${a.contrast}%)`, `saturate(${a.saturation}%)`,
      `hue-rotate(${a.hue}deg)`, `blur(${a.blur}px)`, `sepia(${a.sepia}%)`, `grayscale(${a.grayscale}%)`, `opacity(${a.opacity}%)`,
    ].join(' ');
  }

  interface CropBox { x: number; y: number; w: number; h: number; }

  let images: ImageItem[] = [];
  let idx = 0;
  let zoom = 1;
  let rotation = 0;
  let flipH = false;
  let flipV = false;
  let adj: Adjustments = { ...DEFAULT_ADJ };
  let showAdj = false;
  let fullscreen = false;
  let cropMode = false;
  let cropBox: CropBox | null = null;
  let cropStart: { x: number; y: number } | null = null;
  let imgEl: HTMLImageElement;

  $: current = images[idx] ?? null;
  $: cssFilter = adjToFilter(adj);
  $: transform = `rotate(${rotation}deg) scaleX(${flipH ? -1 : 1}) scaleY(${flipV ? -1 : 1})`;

  async function openFiles() {
    const paths = await SystemBridge.pickFiles([{ name: 'Images', extensions: ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg', 'avif', 'tiff'] }], 'Open Images');
    if (!paths || paths.length === 0) return;
    images = paths.map((p) => ({ path: p, name: p.split('/').pop() ?? p, url: `asset://localhost/${p}` }));
    idx = 0;
    resetEdits();
  }

  function resetEdits() {
    zoom = 1; rotation = 0; flipH = false; flipV = false;
    adj = { ...DEFAULT_ADJ }; cropBox = null; cropMode = false;
  }

  function prev() { idx = Math.max(0, idx - 1); resetEdits(); }
  function next() { idx = Math.min(images.length - 1, idx + 1); resetEdits(); }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'ArrowLeft') prev();
    if (e.key === 'ArrowRight') next();
    if (e.key === '+' || e.key === '=') zoom = Math.min(5, zoom + 0.1);
    if (e.key === '-') zoom = Math.max(0.1, zoom - 0.1);
    if (e.key === '0') zoom = 1;
    if (e.key === 'Escape') { cropMode = false; cropBox = null; fullscreen = false; }
  }

  onMount(() => window.addEventListener('keydown', handleKeyDown));
  onDestroy(() => window.removeEventListener('keydown', handleKeyDown));

  function handleScroll(e: WheelEvent) {
    e.preventDefault();
    zoom = Math.max(0.1, Math.min(5, zoom - e.deltaY * 0.001));
  }

  function onCropMouseDown(e: MouseEvent) {
    if (!cropMode || !imgEl) return;
    const rect = imgEl.getBoundingClientRect();
    cropStart = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    cropBox = null;
  }
  function onCropMouseMove(e: MouseEvent) {
    if (!cropMode || !cropStart || !imgEl) return;
    const rect = imgEl.getBoundingClientRect();
    const cx = e.clientX - rect.left, cy = e.clientY - rect.top;
    cropBox = { x: Math.min(cx, cropStart.x), y: Math.min(cy, cropStart.y), w: Math.abs(cx - cropStart.x), h: Math.abs(cy - cropStart.y) };
  }
  function onCropMouseUp() { cropStart = null; }

  async function exportImage(format: 'png' | 'jpg' = 'png') {
    if (!imgEl || !current) return;
    const img = imgEl;
    const canvas = document.createElement('canvas');
    let w = img.naturalWidth, h = img.naturalHeight;
    if (rotation % 180 !== 0) [w, h] = [h, w];
    canvas.width = w; canvas.height = h;

    const ctx = canvas.getContext('2d')!;
    ctx.filter = cssFilter;
    ctx.translate(w / 2, h / 2);
    ctx.rotate((rotation * Math.PI) / 180);
    ctx.scale(flipH ? -1 : 1, flipV ? -1 : 1);
    ctx.drawImage(img, -img.naturalWidth / 2, -img.naturalHeight / 2);

    if (cropBox && cropBox.w > 0 && cropBox.h > 0) {
      const scaleX = img.naturalWidth / img.clientWidth;
      const scaleY = img.naturalHeight / img.clientHeight;
      const croppedCanvas = document.createElement('canvas');
      croppedCanvas.width = cropBox.w * scaleX;
      croppedCanvas.height = cropBox.h * scaleY;
      croppedCanvas.getContext('2d')!.drawImage(canvas, cropBox.x * scaleX, cropBox.y * scaleY, cropBox.w * scaleX, cropBox.h * scaleY, 0, 0, croppedCanvas.width, croppedCanvas.height);
      canvas.width = croppedCanvas.width;
      canvas.height = croppedCanvas.height;
      canvas.getContext('2d')!.drawImage(croppedCanvas, 0, 0);
    }

    const mime = format === 'jpg' ? 'image/jpeg' : 'image/png';
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = current!.name.replace(/\.[^.]+$/, '') + '-edited.' + format;
      a.click();
      URL.revokeObjectURL(url);
    }, mime, 0.92);
  }

  const sliders: { label: string; key: keyof Adjustments; min: number; max: number; step?: number }[] = [
    { label: 'Brightness', key: 'brightness', min: 0, max: 200 },
    { label: 'Contrast', key: 'contrast', min: 0, max: 200 },
    { label: 'Saturation', key: 'saturation', min: 0, max: 200 },
    { label: 'Hue Rotate', key: 'hue', min: -180, max: 180 },
    { label: 'Blur', key: 'blur', min: 0, max: 20, step: 0.5 },
    { label: 'Sepia', key: 'sepia', min: 0, max: 100 },
    { label: 'Grayscale', key: 'grayscale', min: 0, max: 100 },
    { label: 'Opacity', key: 'opacity', min: 0, max: 100 },
  ];
</script>

<div class="flex flex-col bg-slate-950 text-white overflow-hidden {fullscreen ? 'fixed inset-0 z-50' : 'h-full'}">
  <div class="shrink-0 flex items-center gap-1 px-3 py-2 bg-slate-900 border-b border-white/5">
    <button on:click={openFiles} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Open images"><FolderOpen size={15} /></button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => (zoom = Math.min(5, zoom + 0.15))} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Zoom in (+)"><ZoomIn size={15} /></button>
    <button on:click={() => (zoom = Math.max(0.1, zoom - 0.15))} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Zoom out (-)"><ZoomOut size={15} /></button>
    <button on:click={() => (zoom = 1)} class="px-2 py-1 hover:bg-white/10 rounded-lg text-xs text-slate-400 hover:text-white font-mono">{Math.round(zoom * 100)}%</button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => (rotation -= 90)} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Rotate left"><RotateCcw size={15} /></button>
    <button on:click={() => (rotation += 90)} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Rotate right"><RotateCw size={15} /></button>
    <button on:click={() => (flipH = !flipH)} class="p-1.5 rounded-lg text-sm {flipH ? 'bg-blue-600/25 text-blue-400' : 'hover:bg-white/10 text-slate-400 hover:text-white'}" title="Flip horizontal"><FlipHorizontal size={15} /></button>
    <button on:click={() => (flipV = !flipV)} class="p-1.5 rounded-lg {flipV ? 'bg-blue-600/25 text-blue-400' : 'hover:bg-white/10 text-slate-400 hover:text-white'}" title="Flip vertical"><FlipVertical size={15} /></button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => { cropMode = !cropMode; if (cropMode) cropBox = null; }}
      class="p-1.5 rounded-lg {cropMode ? 'bg-orange-600/25 text-orange-400' : 'hover:bg-white/10 text-slate-400 hover:text-white'}" title="Crop"><Crop size={15} /></button>
    <button on:click={() => (showAdj = !showAdj)} class="p-1.5 rounded-lg {showAdj ? 'bg-blue-600/25 text-blue-400' : 'hover:bg-white/10 text-slate-400 hover:text-white'}" title="Adjustments"><Sliders size={15} /></button>
    <button on:click={() => (adj = { ...DEFAULT_ADJ })} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Reset adjustments"><RefreshCw size={14} /></button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => exportImage('png')} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Export PNG"><Download size={15} /></button>
    <div class="ml-auto flex gap-1">
      {#if current}<span class="text-xs text-slate-600 self-center mr-2 font-mono">{current.name}</span>{/if}
      <button on:click={() => (fullscreen = !fullscreen)} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white">
        {#if fullscreen}<Minimize2 size={15} />{:else}<Maximize2 size={15} />{/if}
      </button>
    </div>
  </div>

  <div class="flex-1 flex overflow-hidden">
    {#if showAdj}
      <div class="w-52 shrink-0 bg-slate-900 border-r border-white/5 overflow-y-auto">
        <div class="p-4 space-y-4">
          <div class="flex items-center justify-between mb-2">
            <span class="text-xs font-medium text-slate-400 uppercase tracking-wider">Adjustments</span>
            <button on:click={() => (showAdj = false)} class="text-slate-600 hover:text-white"><X size={13} /></button>
          </div>
          {#each sliders as s (s.key)}
            <div class="space-y-1">
              <div class="flex justify-between text-xs">
                <span class="text-slate-400">{s.label}</span>
                <span class="text-slate-500 font-mono">{adj[s.key]}</span>
              </div>
              <input type="range" min={s.min} max={s.max} step={s.step ?? 1} value={adj[s.key]}
                on:input={(e) => (adj = { ...adj, [s.key]: parseFloat(e.currentTarget.value) })}
                class="w-full h-1.5 accent-blue-500 cursor-pointer" />
            </div>
          {/each}
          <div class="pt-2 border-t border-white/5 flex gap-2">
            <button on:click={() => exportImage('png')} class="flex-1 py-1.5 bg-blue-600 hover:bg-blue-500 rounded-lg text-xs text-white font-medium">Export PNG</button>
            <button on:click={() => exportImage('jpg')} class="flex-1 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs text-slate-300">Export JPG</button>
          </div>
        </div>
      </div>
    {/if}

    <div class="flex-1 overflow-hidden relative flex items-center justify-center bg-slate-950" on:wheel={handleScroll}>
      {#if !current}
        <div class="flex flex-col items-center gap-4 text-slate-600">
          <ImageIcon size={56} strokeWidth={1} />
          <p class="text-sm">No image open</p>
          <button on:click={openFiles} class="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-xl text-sm text-white">Open images</button>
        </div>
      {:else}
        <div class="relative" on:mousedown={onCropMouseDown} on:mousemove={onCropMouseMove} on:mouseup={onCropMouseUp} style="cursor:{cropMode ? 'crosshair' : 'default'};">
          <img
            bind:this={imgEl}
            src={current.url}
            alt={current.name}
            draggable="false"
            style="transform:scale({zoom}) {transform}; filter:{cssFilter}; max-width:90vw; max-height:70vh; transition:transform 0.15s ease, filter 0.1s ease; user-select:none; transform-origin:center center;"
          />
          {#if cropMode && cropBox && cropBox.w > 0}
            <div style="position:absolute; left:{cropBox.x}px; top:{cropBox.y}px; width:{cropBox.w}px; height:{cropBox.h}px; border:2px dashed #f97316; background:rgba(249,115,22,0.1); pointer-events:none;" />
          {/if}
        </div>
      {/if}

      {#if images.length > 1}
        <button on:click={prev} disabled={idx === 0} class="absolute left-3 top-1/2 -translate-y-1/2 p-2 rounded-xl bg-black/40 hover:bg-black/60 text-white disabled:opacity-20 transition-all"><ChevronLeft size={22} /></button>
        <button on:click={next} disabled={idx === images.length - 1} class="absolute right-3 top-1/2 -translate-y-1/2 p-2 rounded-xl bg-black/40 hover:bg-black/60 text-white disabled:opacity-20 transition-all"><ChevronRight size={22} /></button>
      {/if}
    </div>
  </div>

  {#if images.length > 1}
    <div class="shrink-0 flex gap-1.5 px-3 py-2 bg-slate-900 border-t border-white/5 overflow-x-auto scrollbar-hide">
      {#each images as img, i (img.path)}
        <button on:click={() => { idx = i; resetEdits(); }} class="w-12 h-12 rounded-lg overflow-hidden shrink-0 border-2 transition-all {i === idx ? 'border-blue-500' : 'border-transparent hover:border-slate-500'}">
          <img src={img.url} alt={img.name} class="w-full h-full object-cover" />
        </button>
      {/each}
    </div>
  {/if}

  {#if current}
    <div class="shrink-0 flex items-center justify-between px-4 py-1 bg-slate-900 border-t border-white/5 text-xs text-slate-600">
      <span>{idx + 1} / {images.length}</span>
      <span class="font-mono">{Math.round(zoom * 100)}%{rotation !== 0 ? ` · ${rotation}°` : ''}</span>
      {#if cropMode}<span class="text-orange-500">Crop mode — drag to select</span>{/if}
    </div>
  {/if}
</div>

// src/components/apps/Blue-Images-App/main.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { AppProps } from '../../../types';
import {
    ChevronLeft, ChevronRight, ZoomIn, ZoomOut, RotateCcw, RotateCw,
    Maximize2, Minimize2, FolderOpen, Grid, Image, Info,
    Download, Trash2, FlipHorizontal, FlipVertical, Star, X
} from 'lucide-react';

interface ImageItem { name: string; url: string; file?: File; }

const BlueImagesApp: React.FC<AppProps> = () => {
    const [images, setImages] = useState<ImageItem[]>([]);
    const [idx, setIdx] = useState(0);
    const [zoom, setZoom] = useState(1);
    const [rotation, setRotation] = useState(0);
    const [flipH, setFlipH] = useState(false);
    const [flipV, setFlipV] = useState(false);
    const [view, setView] = useState<'single'|'grid'>('single');
    const [fullscreen, setFullscreen] = useState(false);
    const [showInfo, setShowInfo] = useState(false);
    const [pan, setPan] = useState({x:0,y:0});
    const [dragging, setDragging] = useState(false);
    const [dragStart, setDragStart] = useState({x:0,y:0,px:0,py:0});
    const [imgSize, setImgSize] = useState({w:0,h:0});
    const [favorites, setFavorites] = useState<Set<string>>(new Set());
    const fileInputRef = useRef<HTMLInputElement>(null);
    const containerRef = useRef<HTMLDivElement>(null);

    const current = images[idx] ?? null;
    const resetView = useCallback(()=>{setZoom(1);setRotation(0);setFlipH(false);setFlipV(false);setPan({x:0,y:0});}, []);
    useEffect(()=>{resetView();},[idx]);

    const addFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files||[]).filter(f=>f.type.startsWith('image/'));
        const items = files.map(f=>({name:f.name,url:URL.createObjectURL(f),file:f}));
        setImages(prev=>{if(prev.length===0)setIdx(0);return[...prev,...items];});
        e.target.value='';
    };

    const go = (dir: -1|1) => setIdx(i=>Math.max(0,Math.min(images.length-1,i+dir)));

    useEffect(()=>{
        const handleKey = (e: KeyboardEvent) => {
            if(e.key==='ArrowLeft')go(-1);
            else if(e.key==='ArrowRight')go(1);
            else if(e.key==='+'||e.key==='=')setZoom(z=>Math.min(8,z*1.2));
            else if(e.key==='-')setZoom(z=>Math.max(0.1,z/1.2));
            else if(e.key==='0')resetView();
            else if(e.key==='r')setRotation(r=>(r+90)%360);
            else if(e.key==='Delete')setImages(prev=>{const n=prev.filter((_,i)=>i!==idx);setIdx(i=>Math.min(i,n.length-1));return n;});
        };
        window.addEventListener('keydown',handleKey);
        return()=>window.removeEventListener('keydown',handleKey);
    },[idx,images.length,resetView]);

    const handleWheel = (e: React.WheelEvent) => {
        e.preventDefault();
        setZoom(z=>Math.max(0.1,Math.min(8,z*(e.deltaY<0?1.1:0.9))));
    };

    const startDrag = (e: React.MouseEvent) => { if(zoom<=1)return; setDragging(true); setDragStart({x:e.clientX,y:e.clientY,px:pan.x,py:pan.y}); };
    const doDrag = (e: React.MouseEvent) => { if(!dragging)return; setPan({x:dragStart.px+e.clientX-dragStart.x,y:dragStart.py+e.clientY-dragStart.y}); };
    const endDrag = () => setDragging(false);

    const download=()=>{if(!current)return;const a=document.createElement('a');a.href=current.url;a.download=current.name;a.click();};
    const toggleFullscreen=async()=>{if(!document.fullscreenElement){await containerRef.current?.requestFullscreen();setFullscreen(true);}else{await document.exitFullscreen();setFullscreen(false);}};
    const toggleFav=(name:string)=>setFavorites(prev=>{const n=new Set(prev);n.has(name)?n.delete(name):n.add(name);return n;});

    const transform=`rotate(${rotation}deg) scaleX(${flipH?-1:1}) scaleY(${flipV?-1:1}) scale(${zoom}) translate(${pan.x/zoom}px,${pan.y/zoom}px)`;

    return (
        <div ref={containerRef} className="flex flex-col h-full bg-slate-950 text-white overflow-hidden" onWheel={handleWheel}>
            <input ref={fileInputRef} type="file" multiple accept="image/*" className="hidden" onChange={addFiles}/>
            <div className="shrink-0 flex items-center gap-1 px-3 py-2 bg-slate-900 border-b border-white/5">
                <button onClick={()=>fileInputRef.current?.click()} className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-sm"><FolderOpen size={14}/> Open</button>
                <div className="w-px h-5 bg-white/10 mx-1"/>
                <button onClick={()=>setView(v=>v==='single'?'grid':'single')} className={`p-1.5 rounded-lg ${view==='grid'?'text-blue-400 bg-blue-500/10':'text-slate-400 hover:bg-white/10'}`}><Grid size={16}/></button>
                {view==='single'&&current&&(<>
                    <div className="w-px h-5 bg-white/10 mx-1"/>
                    <button onClick={()=>setZoom(z=>Math.min(8,z*1.25))} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400"><ZoomIn size={15}/></button>
                    <button onClick={()=>setZoom(z=>Math.max(0.1,z/1.25))} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400"><ZoomOut size={15}/></button>
                    <button onClick={resetView} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 text-xs px-2">1:1</button>
                    <div className="w-px h-5 bg-white/10 mx-1"/>
                    <button onClick={()=>setRotation(r=>(r-90+360)%360)} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400"><RotateCcw size={15}/></button>
                    <button onClick={()=>setRotation(r=>(r+90)%360)} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400"><RotateCw size={15}/></button>
                    <button onClick={()=>setFlipH(h=>!h)} className={`p-1.5 rounded-lg ${flipH?'text-blue-400 bg-blue-500/10':'text-slate-400 hover:bg-white/10'}`}><FlipHorizontal size={15}/></button>
                    <button onClick={()=>setFlipV(v=>!v)} className={`p-1.5 rounded-lg ${flipV?'text-blue-400 bg-blue-500/10':'text-slate-400 hover:bg-white/10'}`}><FlipVertical size={15}/></button>
                    <div className="w-px h-5 bg-white/10 mx-1"/>
                    <button onClick={()=>toggleFav(current.name)} className={`p-1.5 rounded-lg ${favorites.has(current.name)?'text-yellow-400':'text-slate-400 hover:bg-white/10'}`}><Star size={15}/></button>
                    <button onClick={download} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400"><Download size={15}/></button>
                    <button onClick={()=>setImages(prev=>{const n=prev.filter((_,i)=>i!==idx);setIdx(i=>Math.min(i,n.length-1));return n;})} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-red-400"><Trash2 size={15}/></button>
                    <div className="w-px h-5 bg-white/10 mx-1"/>
                    <button onClick={()=>setShowInfo(s=>!s)} className={`p-1.5 rounded-lg ${showInfo?'text-blue-400 bg-blue-500/10':'text-slate-400 hover:bg-white/10'}`}><Info size={15}/></button>
                    <button onClick={toggleFullscreen} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400">{fullscreen?<Minimize2 size={15}/>:<Maximize2 size={15}/>}</button>
                </>)}
                <div className="flex-1"/>
                {images.length>0&&<span className="text-xs text-slate-500">{idx+1} / {images.length}</span>}
            </div>

            <div className="flex-1 flex overflow-hidden">
                {view==='grid'?(
                    <div className="flex-1 overflow-y-auto p-3">
                        {images.length===0?(
                            <div className="flex flex-col items-center justify-center h-full gap-4">
                                <Image size={48} className="text-slate-600"/><p className="text-slate-500">No images loaded</p>
                                <button onClick={()=>fileInputRef.current?.click()} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-xl text-sm">Open Images</button>
                            </div>
                        ):(
                            <div className="grid grid-cols-[repeat(auto-fill,minmax(120px,1fr))] gap-2">
                                {images.map((img,i)=>(
                                    <div key={i} onClick={()=>{setIdx(i);setView('single');}} className={`relative aspect-square rounded-xl overflow-hidden cursor-pointer border-2 ${i===idx?'border-blue-500':'border-transparent hover:border-white/20'}`}>
                                        <img src={img.url} className="w-full h-full object-cover" alt={img.name}/>
                                        {favorites.has(img.name)&&<div className="absolute top-1 right-1"><Star size={12} className="text-yellow-400 fill-yellow-400"/></div>}
                                        <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-2 py-1"><p className="text-[10px] text-white truncate">{img.name}</p></div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                ):(
                    <div className="flex-1 flex overflow-hidden">
                        <div className="flex items-center px-2"><button onClick={()=>go(-1)} disabled={idx===0} className="p-2 rounded-xl bg-black/30 hover:bg-black/50 disabled:opacity-20"><ChevronLeft size={20}/></button></div>
                        <div className="flex-1 relative overflow-hidden flex items-center justify-center bg-slate-950"
                            onMouseDown={startDrag} onMouseMove={doDrag} onMouseUp={endDrag} onMouseLeave={endDrag}
                            style={{cursor:zoom>1?(dragging?'grabbing':'grab'):'default'}}>
                            {current?(
                                <img src={current.url} alt={current.name} draggable={false}
                                    onLoad={e=>{const i=e.target as HTMLImageElement;setImgSize({w:i.naturalWidth,h:i.naturalHeight});}}
                                    style={{transform,maxWidth:'100%',maxHeight:'100%',objectFit:'contain',transition:dragging?'none':'transform 0.1s',userSelect:'none'}}/>
                            ):(
                                <div className="flex flex-col items-center gap-4">
                                    <Image size={64} className="text-slate-700"/><p className="text-slate-500">No image</p>
                                    <button onClick={()=>fileInputRef.current?.click()} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-xl text-sm">Open Images</button>
                                </div>
                            )}
                            {zoom!==1&&<div className="absolute top-3 left-3 bg-black/60 backdrop-blur-sm rounded-lg px-2 py-1 text-xs text-white">{Math.round(zoom*100)}%</div>}
                            {showInfo&&current&&(
                                <div className="absolute top-3 right-3 bg-slate-900/95 border border-white/10 rounded-xl p-4 w-48 text-xs space-y-1.5">
                                    <div className="font-semibold text-white truncate">{current.name}</div>
                                    <div className="flex justify-between text-slate-400"><span>Size</span><span className="text-white">{imgSize.w}×{imgSize.h}</span></div>
                                    <div className="flex justify-between text-slate-400"><span>Zoom</span><span className="text-white">{Math.round(zoom*100)}%</span></div>
                                    <div className="flex justify-between text-slate-400"><span>Rotation</span><span className="text-white">{rotation}°</span></div>
                                </div>
                            )}
                            {images.length>1&&(
                                <div className="absolute bottom-3 left-1/2 -translate-x-1/2 flex gap-1.5 bg-black/60 backdrop-blur-sm rounded-xl p-1.5 max-w-xs overflow-x-auto">
                                    {images.slice(Math.max(0,idx-3),idx+4).map((img,i)=>{const realIdx=Math.max(0,idx-3)+i;return(
                                        <div key={realIdx} onClick={()=>setIdx(realIdx)} className={`w-10 h-10 rounded-lg overflow-hidden cursor-pointer border-2 shrink-0 ${realIdx===idx?'border-blue-400 scale-110':'border-transparent opacity-60 hover:opacity-100'}`}>
                                            <img src={img.url} className="w-full h-full object-cover" alt=""/>
                                        </div>
                                    );})}
                                </div>
                            )}
                        </div>
                        <div className="flex items-center px-2"><button onClick={()=>go(1)} disabled={idx===images.length-1} className="p-2 rounded-xl bg-black/30 hover:bg-black/50 disabled:opacity-20"><ChevronRight size={20}/></button></div>
                    </div>
                )}
            </div>

            <div className="shrink-0 flex items-center px-4 py-1.5 bg-slate-900 border-t border-white/5 text-xs text-slate-500 gap-4">
                {current?(<><span className="truncate">{current.name}</span>{imgSize.w>0&&<span>{imgSize.w}×{imgSize.h}</span>}<span>{Math.round(zoom*100)}%</span><span className="ml-auto">← → Navigate · Scroll Zoom · 0 Reset</span></>):<span>Blue Images — Open image files to view</span>}
            </div>
        </div>
    );
};
export default BlueImagesApp;
