// src/components/apps/Settings-App/sections/NightLightSection.tsx
import React from 'react';
import type { UserConfig } from '../../../../types';
import { applyNightLight } from '../display_helpers';

interface Props { config: UserConfig; onSave: (p: Partial<UserConfig>) => Promise<void>; }

const NightLightSection: React.FC<Props> = ({ config, onSave }) => (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
        <h2 className="text-2xl font-bold text-white">Night Light</h2>
        <div className="bg-slate-800 p-6 rounded-2xl border border-white/5">
            <div className="flex items-center justify-between mb-4">
                <label className="text-sm font-medium text-slate-400">Night Light</label>
                <input type="checkbox" checked={config.nightLightEnabled ?? false}
                    onChange={async e => {
                        const v = e.target.checked;
                        await onSave({ nightLightEnabled: v });
                        await applyNightLight(v, config.nightLightTemperature ?? 4000);
                    }}
                    className="w-4 h-4 accent-blue-500" />
            </div>
            {config.nightLightEnabled && (
                <div>
                    <label className="block text-sm font-medium text-slate-400 mb-1">Color Temperature (K)</label>
                    <input type="range" min="1000" max="10000" step="100"
                        value={config.nightLightTemperature ?? 4000}
                        onChange={async e => {
                            const v = parseInt(e.target.value);
                            await onSave({ nightLightTemperature: v });
                            await applyNightLight(true, v);
                        }}
                        className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-orange-400" />
                    <div className="flex justify-between text-xs text-slate-500 mt-1">
                        <span>🕯️ 1000K</span>
                        <span>{config.nightLightTemperature ?? 4000}K</span>
                        <span>☀️ 10000K</span>
                    </div>
                </div>
            )}
        </div>
    </div>
);
export default NightLightSection;

// src/lib/components/apps/Settings-App/sections/NightLightSection.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { UserConfig } from '../../../../types';
  import { applyNightLight, getGeoLocation, computeSunTimes, type GeoCoords } from '../display_helpers';

  export let config: UserConfig;
  export let onSave: (p: Partial<UserConfig>) => Promise<void>;

  let geo: GeoCoords | null = null;
  let geoDenied = false;
  let sunTimes: { sunrise: string; sunset: string } | null = null;

  $: schedule = config.nightLightSchedule ?? 'manual';

  async function resolveGeo() {
    geo = await getGeoLocation();
    geoDenied = !geo;
    sunTimes = geo ? computeSunTimes(geo.lat, geo.lon) : null;
  }

  onMount(() => {
    if (schedule === 'sunset') resolveGeo();
  });

  async function toggle(e: Event) {
    const v = (e.currentTarget as HTMLInputElement).checked;
    await onSave({ nightLightEnabled: v });
    await applyNightLight(v, config.nightLightTemperature ?? 4000, schedule, geo);
  }

  async function changeTemp(e: Event) {
    const v = parseInt((e.currentTarget as HTMLInputElement).value);
    await onSave({ nightLightTemperature: v });
    await applyNightLight(true, v, schedule, geo);
  }

  async function changeSchedule(mode: 'manual' | 'sunset') {
    await onSave({ nightLightSchedule: mode });
    if (mode === 'sunset' && !geo) await resolveGeo();
    if (config.nightLightEnabled) await applyNightLight(true, config.nightLightTemperature ?? 4000, mode, geo);
  }

  async function changeHour(field: 'nightLightStartHour' | 'nightLightEndHour', e: Event) {
    const v = parseInt((e.currentTarget as HTMLSelectElement).value);
    await onSave({ [field]: v } as Partial<UserConfig>);
  }
</script>

<div class="space-y-6">
  <h2 class="text-2xl font-bold text-white">Night Light</h2>
  <div class="bg-slate-800 p-6 rounded-2xl border border-white/5 space-y-5">
    <div class="flex items-center justify-between">
      <label class="text-sm font-medium text-slate-400">Night Light</label>
      <input type="checkbox" checked={config.nightLightEnabled ?? false} on:change={toggle} class="w-4 h-4 accent-blue-500" />
    </div>

    {#if config.nightLightEnabled}
      <div>
        <label class="block text-sm font-medium text-slate-400 mb-1">Color Temperature (K)</label>
        <input type="range" min="1000" max="10000" step="100" value={config.nightLightTemperature ?? 4000} on:change={changeTemp}
          class="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-orange-400" />
        <div class="flex justify-between text-xs text-slate-500 mt-1">
          <span>1000K</span>
          <span>{config.nightLightTemperature ?? 4000}K</span>
          <span>10000K</span>
        </div>
      </div>

      <div>
        <label class="block text-sm font-medium text-slate-400 mb-2">Schedule</label>
        <div class="flex gap-2">
          <button on:click={() => changeSchedule('manual')}
            class="flex-1 py-2 rounded-lg text-sm border {schedule === 'manual' ? 'bg-blue-600/20 border-blue-500 text-blue-400' : 'border-white/10 text-slate-400 hover:bg-white/5'}">
            Manual
          </button>
          <button on:click={() => changeSchedule('sunset')}
            class="flex-1 py-2 rounded-lg text-sm border {schedule === 'sunset' ? 'bg-blue-600/20 border-blue-500 text-blue-400' : 'border-white/10 text-slate-400 hover:bg-white/5'}">
            Sunset to sunrise
          </button>
        </div>
      </div>

      {#if schedule === 'sunset'}
        <div class="rounded-xl bg-slate-900/60 border border-white/5 p-3 text-xs text-slate-400 space-y-1.5">
          {#if geo && sunTimes}
            <div class="flex justify-between"><span>Sunset today</span><span class="text-slate-200">{sunTimes.sunset}</span></div>
            <div class="flex justify-between"><span>Sunrise tomorrow</span><span class="text-slate-200">{sunTimes.sunrise}</span></div>
            <div class="text-[11px] text-slate-500 pt-1">Based on your device location ({geo.lat.toFixed(2)}, {geo.lon.toFixed(2)}). Recalculated automatically every day.</div>
          {:else if geoDenied}
            <div class="text-amber-400">Location unavailable — using a fixed fallback window (19:00–07:00).</div>
            <button on:click={resolveGeo} class="text-blue-400 hover:underline">Try location again</button>
          {:else}
            <div>Resolving sunrise/sunset for your location…</div>
          {/if}
        </div>
      {:else}
        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="block text-xs text-slate-500 mb-1">Start hour</label>
            <select value={config.nightLightStartHour ?? 20} on:change={(e) => changeHour('nightLightStartHour', e)}
              class="w-full bg-slate-900 border border-white/10 rounded-lg px-2 py-1.5 text-sm">
              {#each Array(24) as _, h}<option value={h}>{String(h).padStart(2, '0')}:00</option>{/each}
            </select>
          </div>
          <div>
            <label class="block text-xs text-slate-500 mb-1">End hour</label>
            <select value={config.nightLightEndHour ?? 6} on:change={(e) => changeHour('nightLightEndHour', e)}
              class="w-full bg-slate-900 border border-white/10 rounded-lg px-2 py-1.5 text-sm">
              {#each Array(24) as _, h}<option value={h}>{String(h).padStart(2, '0')}:00</option>{/each}
            </select>
          </div>
        </div>
      {/if}
    {/if}
  </div>
</div>
