// src/lib/components/apps/Explorer-App/ExplorerApp.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from 'svelte';
  import {
    Folder, HardDrive, ArrowLeft, ArrowRight, RefreshCw,
    Plus, Trash2, Copy, Clipboard, Scissors, Home, Image,
    Music, Video, FileText, Download, ChevronRight,
    Grid, List, Eye, X, Edit, Search,
    SortAsc, SortDesc, Columns, Info, Check, AlertCircle, Loader2,
  } from 'lucide-svelte';
  import { SystemBridge } from '../../../utils/systemBridge';
  import { dialogPrompt, dialogConfirm } from '../../../stores/dialog';
  import type { FileEntry, Tab, Notif, SortKey } from './types';
  import { BOOKMARKS } from './types';
  import FileIcon from './FileIcon.svelte';
  import RightPane from './RightPane.svelte';

  const BM_ICONS: Record<string, any> = { Home, Folder, FileText, Download, Image, Music, Video };
  const BOOKMARKS_WITH_ICONS = BOOKMARKS.map((bm) => ({ ...bm, icon: BM_ICONS[bm.iconName] ?? Folder }));

  let tabs: Tab[] = [{ id: 'tab-1', path: 'HOME', history: ['HOME'], historyIndex: 0 }];
  let activeTabId = 'tab-1';
  let dualPane = false;
  let rightPath = 'HOME';

  let files: FileEntry[] = [];
  let loading = false;
  let selected = new Set<string>();
  let lastSel: string | null = null;

  let viewMode: 'grid' | 'list' = 'grid';
  let showHidden = false;
  let sortBy: SortKey = 'name';
  let sortAsc = true;
  let searchTerm = '';
  let showSearch = false;

  let clipboard: { action: 'copy' | 'cut'; files: string[] } | null = null;
  let previewFile: FileEntry | null = null;
  let previewContent = '';
  let previewLoading = false;
  let thumbnails: Record<string, string> = {};
  let notifs: Notif[] = [];
  let renaming: string | null = null;
  let renameVal = '';
  let dragOver: string | null = null;

  let gridEl: HTMLDivElement;
  let searchEl: HTMLInputElement;
  let renameEl: HTMLInputElement;

  $: activeTab = tabs.find((t) => t.id === activeTabId) ?? tabs[0];

  function notify(type: Notif['type'], message: string) {
    const id = Date.now().toString();
    notifs = [...notifs, { id, type, message }];
    setTimeout(() => (notifs = notifs.filter((n) => n.id !== id)), 3500);
  }

  async function loadFiles(path: string) {
    loading = true; selected = new Set(); previewFile = null;
    try {
      const entries = await SystemBridge.getFiles(path);
      files = entries;
      for (const e of entries.filter((e: FileEntry) => e.mime_type.startsWith('image/')).slice(0, 24)) {
        if (!thumbnails[e.path]) {
          SystemBridge.readFileAsDataURL(e.path).then((d: string | null) => { if (d) thumbnails = { ...thumbnails, [e.path]: d }; }).catch(() => {});
        }
      }
    } catch { notify('error', `Cannot open: ${path}`); }
    finally { loading = false; }
  }

  function navigateTo(path: string) {
    tabs = tabs.map((t) => {
      if (t.id !== activeTabId) return t;
      const h = t.history.slice(0, t.historyIndex + 1);
      h.push(path);
      return { ...t, path, history: h, historyIndex: h.length - 1 };
    });
    loadFiles(path);
  }

  onMount(() => loadFiles(activeTab.path));

  function goBack() {
    const t = activeTab;
    if (t.historyIndex <= 0) return;
    const ni = t.historyIndex - 1, np = t.history[ni];
    tabs = tabs.map((tb) => (tb.id === activeTabId ? { ...tb, historyIndex: ni, path: np } : tb));
    loadFiles(np);
  }
  function goForward() {
    const t = activeTab;
    if (t.historyIndex >= t.history.length - 1) return;
    const ni = t.historyIndex + 1, np = t.history[ni];
    tabs = tabs.map((tb) => (tb.id === activeTabId ? { ...tb, historyIndex: ni, path: np } : tb));
    loadFiles(np);
  }
  function goUp() {
    const cur = activeTab.path;
    if (cur === 'HOME' || cur === '/') return;
    const parent = cur.includes('/') ? cur.split('/').slice(0, -1).join('/') || '/' : 'HOME';
    navigateTo(parent);
  }

  function addTab() {
    const id = `tab-${Date.now()}`;
    tabs = [...tabs, { id, path: 'HOME', history: ['HOME'], historyIndex: 0 }];
    activeTabId = id;
    loadFiles('HOME');
  }
  function closeTab(id: string) {
    if (tabs.length === 1) return;
    const next = tabs.filter((t) => t.id !== id);
    tabs = next;
    if (activeTabId === id) {
      const n = next[next.length - 1];
      activeTabId = n.id;
      loadFiles(n.path);
    }
  }

  function handleOpen(file: FileEntry) {
    if (file.is_dir) { navigateTo(file.path); return; }
    if (file.mime_type.startsWith('image/') || file.mime_type.startsWith('text/')) openPreview(file);
    else SystemBridge.launchApp(`xdg-open "${file.path}"`);
  }

  async function createFolder() {
    const name = await dialogPrompt({ title: 'New Folder', placeholder: 'Untitled Folder', defaultValue: 'New Folder', confirmLabel: 'Create' });
    if (!name?.trim()) return;
    try { await SystemBridge.createFolder(activeTab.path, name.trim()); notify('success', `Created: ${name}`); loadFiles(activeTab.path); }
    catch { notify('error', 'Failed to create folder'); }
  }

  async function deleteSelected() {
    if (selected.size === 0) return;
    const ok = await dialogConfirm({ title: 'Delete items', message: `Delete ${selected.size} item(s)? This cannot be undone.`, confirmLabel: 'Delete', danger: true });
    if (!ok) return;
    let errors = 0;
    for (const path of selected) { try { await SystemBridge.deleteFile(path); } catch { errors++; } }
    notify(errors ? 'error' : 'success', errors ? `${errors} item(s) failed` : `Deleted ${selected.size} item(s)`);
    selected = new Set();
    loadFiles(activeTab.path);
  }

  function copySelected() { if (!selected.size) return; clipboard = { action: 'copy', files: [...selected] }; notify('info', `Copied ${selected.size} item(s)`); }
  function cutSelected() { if (!selected.size) return; clipboard = { action: 'cut', files: [...selected] }; notify('info', `Cut ${selected.size} item(s)`); }

  async function paste() {
    if (!clipboard) return;
    let errors = 0;
    for (const src of clipboard.files) {
      const name = src.split('/').pop() ?? '';
      const dst = `${activeTab.path}/${name}`;
      try { if (clipboard.action === 'copy') await SystemBridge.copyFile(src, dst); else await SystemBridge.moveFile(src, dst); }
      catch { errors++; }
    }
    notify(errors ? 'error' : 'success', errors ? `${errors} item(s) failed` : `Pasted ${clipboard.files.length} item(s)`);
    if (clipboard.action === 'cut') clipboard = null;
    loadFiles(activeTab.path);
  }

  async function startRename(file: FileEntry) {
    renaming = file.path; renameVal = file.name;
    await tick();
    renameEl?.select();
  }
  async function commitRename() {
    if (!renaming || !renameVal.trim()) { renaming = null; return; }
    const file = files.find((f) => f.path === renaming);
    if (!file || renameVal === file.name) { renaming = null; return; }
    const newPath = renaming.slice(0, renaming.lastIndexOf('/') + 1) + renameVal.trim();
    try { await SystemBridge.moveFile(renaming, newPath); notify('success', `Renamed to: ${renameVal}`); loadFiles(activeTab.path); }
    catch { notify('error', 'Rename failed'); }
    finally { renaming = null; }
  }

  async function openPreview(file: FileEntry) {
    previewFile = file; previewLoading = true;
    try {
      if (file.mime_type.startsWith('image/')) previewContent = (await SystemBridge.readFileAsDataURL(file.path)) ?? '';
      else previewContent = await SystemBridge.readFile(file.path);
    } catch { previewContent = ''; }
    finally { previewLoading = false; }
  }

  function toggleSelect(path: string, e?: MouseEvent) {
    if (renaming) return;
    if (e?.shiftKey && lastSel) {
      const i1 = sorted.findIndex((f) => f.path === lastSel);
      const i2 = sorted.findIndex((f) => f.path === path);
      const [a, b] = [Math.min(i1, i2), Math.max(i1, i2)];
      selected = new Set(sorted.slice(a, b + 1).map((f) => f.path));
    } else if (e?.ctrlKey || e?.metaKey) {
      const n = new Set(selected);
      n.has(path) ? n.delete(path) : n.add(path);
      selected = n;
    } else {
      selected = new Set([path]);
    }
    lastSel = path;
  }

  $: filtered = files.filter((f) => showHidden || !f.name.startsWith('.')).filter((f) => !searchTerm || f.name.toLowerCase().includes(searchTerm.toLowerCase()));
  $: sorted = [...filtered].sort((a, b) => {
    if (a.is_dir !== b.is_dir) return a.is_dir ? -1 : 1;
    let cmp = 0;
    if (sortBy === 'name') cmp = a.name.localeCompare(b.name);
    else if (sortBy === 'size') cmp = (parseFloat(a.size) || 0) - (parseFloat(b.size) || 0);
    else if (sortBy === 'modified') cmp = (a.modified ?? '').localeCompare(b.modified ?? '');
    else if (sortBy === 'type') cmp = a.mime_type.localeCompare(b.mime_type);
    return sortAsc ? cmp : -cmp;
  });

  function toggleSort(k: SortKey) { if (sortBy === k) sortAsc = !sortAsc; else { sortBy = k; sortAsc = true; } }
  function toggleSortByKey(k: string) { toggleSort(k as SortKey); }


  function onDragStart(e: DragEvent, file: FileEntry) {
    const paths = selected.has(file.path) ? [...selected] : [file.path];
    e.dataTransfer?.setData('text/plain', JSON.stringify(paths));
    if (e.dataTransfer) e.dataTransfer.effectAllowed = 'copyMove';
  }
  async function onDrop(e: DragEvent, targetDir: FileEntry | null) {
    e.preventDefault(); dragOver = null;
    const dest = targetDir?.path ?? activeTab.path;
    try {
      const paths: string[] = JSON.parse(e.dataTransfer?.getData('text/plain') ?? '[]');
      const isCopy = e.ctrlKey;
      for (const src of paths) {
        const name = src.split('/').pop() ?? '';
        const dst = `${dest}/${name}`;
        if (isCopy) await SystemBridge.copyFile(src, dst); else await SystemBridge.moveFile(src, dst);
      }
      notify('success', `${e.ctrlKey ? 'Copied' : 'Moved'} ${paths.length} item(s)`);
      loadFiles(activeTab.path);
    } catch { notify('error', 'Drop failed'); }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (renaming) return;
    if (e.ctrlKey) {
      if (e.key === 'a') { e.preventDefault(); selected = new Set(sorted.map((f) => f.path)); }
      if (e.key === 'c') { e.preventDefault(); copySelected(); }
      if (e.key === 'x') { e.preventDefault(); cutSelected(); }
      if (e.key === 'v') { e.preventDefault(); paste(); }
      if (e.key === 'f') { e.preventDefault(); showSearch = !showSearch; setTimeout(() => searchEl?.focus(), 50); }
      if (e.key === 'n') { e.preventDefault(); createFolder(); }
      if (e.key === 't') { e.preventDefault(); addTab(); }
    }
    if (e.key === 'F2' && selected.size === 1) {
      const f = files.find((f) => selected.has(f.path));
      if (f) startRename(f);
    }
    if (e.key === 'Delete') { e.preventDefault(); deleteSelected(); }
    if (e.key === 'Escape') { searchTerm = ''; showSearch = false; selected = new Set(); }
  }
  onMount(() => window.addEventListener('keydown', handleKeyDown));
  onDestroy(() => window.removeEventListener('keydown', handleKeyDown));

  $: breadcrumbs = activeTab.path.split('/').map((part, i, arr) => ({
    label: part === 'HOME' ? '~' : part,
    path: arr.slice(0, i + 1).join('/') || '/',
  }));
</script>

<div class="flex h-full bg-slate-900 text-white overflow-hidden" on:dragover={(e) => e.preventDefault()} on:drop={(e) => onDrop(e, null)}>
  <div class="fixed top-16 right-4 z-50 flex flex-col gap-2 pointer-events-none">
    {#each notifs as n (n.id)}
      <div class="flex items-center gap-2 px-4 py-2 rounded-xl shadow-lg text-sm {n.type === 'success' ? 'bg-green-600/90' : n.type === 'error' ? 'bg-red-600/90' : 'bg-slate-700/90'}">
        {#if n.type === 'success'}<Check size={13} />{:else if n.type === 'error'}<AlertCircle size={13} />{:else}<Info size={13} />{/if}
        {n.message}
      </div>
    {/each}
  </div>

  <div class="w-44 bg-slate-800/50 border-r border-white/5 flex flex-col shrink-0">
    <div class="p-3 border-b border-white/5"><span class="text-xs font-semibold text-slate-400 uppercase tracking-wider">Places</span></div>
    <div class="flex-1 overflow-y-auto p-2 space-y-0.5">
      {#each BOOKMARKS_WITH_ICONS as bm (bm.path)}
        <button on:click={() => navigateTo(bm.path)} class="w-full flex items-center gap-2 px-2 py-1.5 rounded-lg text-sm transition-colors {activeTab.path === bm.path ? 'bg-blue-600/20 text-blue-400' : 'text-slate-400 hover:bg-white/5 hover:text-white'}">
          <svelte:component this={bm.icon} size={14} />{bm.name}
        </button>
      {/each}
      <div class="h-px bg-white/5 my-2" />
      <button on:click={() => navigateTo('/')} class="w-full flex items-center gap-2 px-2 py-1.5 rounded-lg text-sm text-slate-400 hover:bg-white/5 hover:text-white">
        <HardDrive size={14} /> / (root)
      </button>
    </div>
  </div>

  <div class="flex-1 flex flex-col min-w-0">
    <div class="flex items-center bg-slate-800/80 border-b border-white/5 overflow-x-auto shrink-0">
      {#each tabs as t (t.id)}
        <div on:click={() => { activeTabId = t.id; loadFiles(t.path); }}
          class="flex items-center gap-1.5 px-3 py-2 cursor-pointer border-r border-white/5 shrink-0 group max-w-[140px] {t.id === activeTabId ? 'bg-slate-900 text-white' : 'text-slate-400 hover:text-white hover:bg-slate-700/50'}">
          <Folder size={12} />
          <span class="text-xs truncate">{t.path === 'HOME' ? '~' : t.path.split('/').pop()}</span>
          {#if tabs.length > 1}
            <button on:click|stopPropagation={() => closeTab(t.id)} class="opacity-0 group-hover:opacity-100 hover:text-red-400 ml-auto shrink-0"><X size={10} /></button>
          {/if}
        </div>
      {/each}
      <button on:click={addTab} class="p-2 text-slate-500 hover:text-white shrink-0"><Plus size={12} /></button>
      <div class="ml-auto pr-2">
        <button on:click={() => (dualPane = !dualPane)} title="Dual pane" class="p-1.5 rounded {dualPane ? 'text-blue-400' : 'text-slate-500 hover:text-white'}"><Columns size={13} /></button>
      </div>
    </div>

    <div class="h-11 bg-slate-800 border-b border-white/5 flex items-center px-2 gap-1 shrink-0">
      <button on:click={goBack} disabled={activeTab.historyIndex === 0} class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><ArrowLeft size={15} /></button>
      <button on:click={goForward} disabled={activeTab.historyIndex >= activeTab.history.length - 1} class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><ArrowRight size={15} /></button>
      <button on:click={goUp} class="p-1.5 hover:bg-white/10 rounded"><HardDrive size={15} /></button>
      <button on:click={() => loadFiles(activeTab.path)} class="p-1.5 hover:bg-white/10 rounded"><RefreshCw size={15} class={loading ? 'animate-spin' : ''} /></button>
      <div class="w-px h-5 bg-white/10 mx-1" />
      <button on:click={createFolder} title="New folder (Ctrl+N)" class="p-1.5 hover:bg-white/10 rounded"><Plus size={15} /></button>
      <button on:click={deleteSelected} disabled={!selected.size} title="Delete (Del)" class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><Trash2 size={15} /></button>
      <button on:click={copySelected} disabled={!selected.size} title="Copy (Ctrl+C)" class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><Copy size={15} /></button>
      <button on:click={cutSelected} disabled={!selected.size} title="Cut (Ctrl+X)" class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><Scissors size={15} /></button>
      <button on:click={paste} disabled={!clipboard} title="Paste (Ctrl+V)" class="p-1.5 hover:bg-white/10 rounded disabled:opacity-30"><Clipboard size={15} class={clipboard ? 'text-blue-400' : ''} /></button>
      <div class="w-px h-5 bg-white/10 mx-1" />
      <div class="flex items-center text-sm flex-1 min-w-0 overflow-hidden">
        {#each breadcrumbs as crumb, i (i)}
          {#if i > 0}<ChevronRight size={11} class="mx-0.5 text-slate-600 shrink-0" />{/if}
          <button on:click={() => navigateTo(crumb.path)} class="hover:text-blue-400 transition-colors shrink-0 truncate max-w-[80px]">{crumb.label}</button>
        {/each}
      </div>
      <div class="flex items-center gap-1 ml-auto shrink-0">
        <button on:click={() => { showSearch = !showSearch; setTimeout(() => searchEl?.focus(), 50); }} class="p-1.5 rounded {showSearch ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}"><Search size={15} /></button>
        <button on:click={() => (showHidden = !showHidden)} class="p-1.5 rounded {showHidden ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}" title="Show hidden"><Eye size={15} /></button>
        <button on:click={() => (viewMode = 'grid')} class="p-1.5 rounded {viewMode === 'grid' ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}"><Grid size={15} /></button>
        <button on:click={() => (viewMode = 'list')} class="p-1.5 rounded {viewMode === 'list' ? 'bg-blue-600/20 text-blue-400' : 'hover:bg-white/10'}"><List size={15} /></button>
      </div>
    </div>

    {#if showSearch}
      <div class="flex items-center gap-2 px-3 py-1.5 bg-slate-800/50 border-b border-white/5">
        <Search size={13} class="text-slate-500 shrink-0" />
        <input bind:this={searchEl} type="text" bind:value={searchTerm} placeholder="Search in current folder…" class="flex-1 bg-transparent text-sm focus:outline-none placeholder-slate-600" />
        {#if searchTerm}<span class="text-xs text-slate-500 shrink-0">{sorted.length}</span>{/if}
        <button on:click={() => { searchTerm = ''; showSearch = false; }}><X size={13} class="text-slate-500" /></button>
      </div>
    {/if}

    <div class="flex-1 flex overflow-hidden">
      <div bind:this={gridEl} class="flex-1 overflow-auto p-2" on:click={(e) => { if (e.target === gridEl) selected = new Set(); }}>
        {#if loading}
          <div class="flex items-center justify-center h-full"><Loader2 size={22} class="animate-spin text-blue-400" /></div>
        {:else if sorted.length === 0}
          <div class="flex flex-col items-center justify-center h-full text-slate-600 gap-2"><Folder size={36} /><span class="text-sm">{searchTerm ? 'No results' : 'Empty folder'}</span></div>
        {:else if viewMode === 'grid'}
          <div class="grid gap-1" style="grid-template-columns:repeat(auto-fill, minmax(88px, 1fr));">
            {#each sorted as file (file.path)}
              {@const isSel = selected.has(file.path)}
              {@const isDragTgt = dragOver === file.path && file.is_dir}
              {@const isCut = clipboard?.action === 'cut' && clipboard.files.includes(file.path)}
              <div draggable="true"
                on:dragstart={(e) => onDragStart(e, file)}
                on:dragover={(e) => { if (file.is_dir) { e.preventDefault(); dragOver = file.path; } }}
                on:drop={(e) => file.is_dir && onDrop(e, file)}
                on:dragleave={() => (dragOver = null)}
                class="relative flex flex-col items-center p-2 rounded-xl cursor-pointer transition-colors duration-100 select-none {isSel ? 'bg-blue-600/30 ring-2 ring-blue-500/60' : 'hover:bg-white/5'} {isDragTgt ? 'bg-blue-500/20 ring-2 ring-blue-400' : ''} {isCut ? 'opacity-50' : ''}"
                on:click|stopPropagation={(e) => toggleSelect(file.path, e)}
                on:dblclick={() => !renaming && handleOpen(file)}>
                <div class="mb-1.5">
                  {#if file.mime_type.startsWith('image/') && thumbnails[file.path]}
                    <img src={thumbnails[file.path]} alt={file.name} class="w-12 h-12 object-cover rounded-lg" />
                  {:else}
                    <FileIcon {file} size={40} />
                  {/if}
                </div>
                {#if renaming === file.path}
                  <input bind:this={renameEl} bind:value={renameVal} on:blur={commitRename}
                    on:keydown={(e) => { if (e.key === 'Enter') commitRename(); if (e.key === 'Escape') renaming = null; e.stopPropagation(); }}
                    class="w-full text-xs text-center bg-slate-800 border border-blue-500 rounded px-1 focus:outline-none" autofocus on:click|stopPropagation />
                {:else}
                  <span class="text-xs text-center break-all line-clamp-2 leading-tight px-1">{file.name}</span>
                {/if}
                <span class="text-[10px] text-slate-600 mt-0.5">{file.size}</span>
              </div>
            {/each}
          </div>
        {:else}
          <table class="w-full text-sm border-collapse">
            <thead class="sticky top-0 bg-slate-800 z-10 text-slate-400 text-xs">
              <tr>
                {#each [['Name', 'name'], ['Size', 'size'], ['Modified', 'modified'], ['Type', 'type']] as [label, sk] (sk)}
                  <th class="p-2 text-left cursor-pointer hover:text-white select-none whitespace-nowrap" on:click={() => toggleSortByKey(sk)}>
                    <span class="flex items-center gap-1">{label} {#if sortBy === sk}{#if sortAsc}<SortAsc size={11} />{:else}<SortDesc size={11} />{/if}{/if}</span>
                  </th>
                {/each}
                <th class="w-14" />
              </tr>
            </thead>
            <tbody>
              {#each sorted as file (file.path)}
                {@const isSel = selected.has(file.path)}
                {@const isDragTgt = dragOver === file.path && file.is_dir}
                {@const isCut = clipboard?.action === 'cut' && clipboard.files.includes(file.path)}
                <tr draggable="true"
                  on:dragstart={(e) => onDragStart(e, file)}
                  on:dragover={(e) => { if (file.is_dir) { e.preventDefault(); dragOver = file.path; } }}
                  on:drop={(e) => file.is_dir && onDrop(e, file)}
                  on:dragleave={() => (dragOver = null)}
                  class="border-b border-white/5 cursor-pointer group {isSel ? 'bg-blue-600/20' : 'hover:bg-white/5'} {isDragTgt ? 'bg-blue-500/15' : ''} {isCut ? 'opacity-50' : ''}"
                  on:click={(e) => toggleSelect(file.path, e)}
                  on:dblclick={() => handleOpen(file)}>
                  <td class="p-2">
                    <div class="flex items-center gap-2 min-w-0">
                      {#if file.mime_type.startsWith('image/') && thumbnails[file.path]}
                        <img src={thumbnails[file.path]} alt="" class="w-5 h-5 object-cover rounded shrink-0" />
                      {:else}
                        <FileIcon {file} size={16} />
                      {/if}
                      {#if renaming === file.path}
                        <input bind:this={renameEl} bind:value={renameVal} on:blur={commitRename}
                          on:keydown={(e) => { if (e.key === 'Enter') commitRename(); if (e.key === 'Escape') renaming = null; e.stopPropagation(); }}
                          class="flex-1 bg-slate-800 border border-blue-500 rounded px-1 text-sm focus:outline-none" autofocus on:click|stopPropagation />
                      {:else}
                        <span class="text-sm truncate">{file.name}</span>
                      {/if}
                    </div>
                  </td>
                  <td class="p-2 text-sm text-slate-500 whitespace-nowrap">{file.size}</td>
                  <td class="p-2 text-sm text-slate-500 whitespace-nowrap">{file.modified ?? '—'}</td>
                  <td class="p-2 text-xs text-slate-600 max-w-[100px] truncate">{file.mime_type}</td>
                  <td class="p-2">
                    <div class="flex gap-1 opacity-0 group-hover:opacity-100">
                      <button on:click|stopPropagation={() => startRename(file)} class="p-1 hover:bg-white/10 rounded text-slate-400"><Edit size={12} /></button>
                      <button on:click|stopPropagation={() => { selected = new Set([file.path]); setTimeout(deleteSelected, 0); }} class="p-1 hover:bg-red-500/20 rounded text-red-400"><Trash2 size={12} /></button>
                    </div>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        {/if}
      </div>

      {#if previewFile}
        {@const pf = previewFile}
        <div class="w-60 border-l border-white/5 bg-slate-800/50 flex flex-col shrink-0">
          <div class="flex items-center justify-between p-2 border-b border-white/5">
            <span class="text-xs font-medium truncate">{pf.name}</span>
            <button on:click={() => (previewFile = null)} class="p-1 hover:bg-white/10 rounded shrink-0"><X size={12} /></button>
          </div>
          <div class="flex-1 overflow-auto p-2">
            <div class="text-[10px] text-slate-500 mb-2 space-y-0.5">
              <div>Size: {pf.size}</div>
              <div>Modified: {pf.modified ?? '—'}</div>
            </div>
            {#if previewLoading}
              <Loader2 size={16} class="animate-spin text-blue-400" />
            {:else if pf.mime_type.startsWith('image/') && previewContent}
              <img src={previewContent} alt="preview" class="max-w-full rounded object-contain" />
            {:else if pf.mime_type.startsWith('text/') && previewContent}
              <pre class="text-[10px] bg-slate-900 p-2 rounded overflow-auto max-h-64 font-mono">{previewContent.slice(0, 3000)}</pre>
            {:else}
              <div class="text-center text-slate-600 text-xs py-4">No preview</div>
            {/if}
          </div>
          <div class="p-2 border-t border-white/5 flex gap-1.5">
            <button on:click={() => SystemBridge.launchApp(`xdg-open "${pf.path}"`)} class="flex-1 py-1 bg-blue-600 hover:bg-blue-500 rounded text-xs">Open</button>
            <button on:click={() => startRename(pf)} class="p-1.5 hover:bg-white/10 rounded"><Edit size={12} /></button>
            <button on:click={() => { selected = new Set([pf.path]); deleteSelected(); previewFile = null; }} class="p-1.5 hover:bg-red-500/20 rounded text-red-400"><Trash2 size={12} /></button>
          </div>
        </div>
      {/if}

      {#if dualPane}
        <div class="w-72 border-l border-white/5 bg-slate-900 flex flex-col shrink-0">
          <div class="flex items-center gap-2 p-2 bg-slate-800 border-b border-white/5 text-xs text-slate-400">
            <Columns size={11} />
            <span class="truncate flex-1">{rightPath}</span>
            <button on:click={() => { rightPath = rightPath.includes('/') ? rightPath.split('/').slice(0, -1).join('/') || '/' : 'HOME'; }} class="hover:text-white shrink-0"><ArrowLeft size={11} /></button>
          </div>
          <RightPane path={rightPath} {thumbnails} on:navigate={(e) => (rightPath = e.detail)} />
        </div>
      {/if}
    </div>

    <div class="h-5 border-t border-white/5 bg-slate-800/50 flex items-center px-3 gap-4 text-[11px] text-slate-600 shrink-0">
      <span>{sorted.length} items</span>
      {#if selected.size > 0}<span>{selected.size} selected</span>{/if}
      {#if clipboard}<span class="text-blue-500">{clipboard.action === 'copy' ? 'Copied' : 'Cut'} {clipboard.files.length}</span>{/if}
      <span class="ml-auto">{activeTab.path}</span>
    </div>
  </div>
</div>

// src/components/apps/ExplorerApp.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { AppProps } from '../../types';
import { SystemBridge } from '../../utils/systemBridge';
import {
    Folder, File, ChevronRight, ChevronLeft, Home, RefreshCw,
    Grid, List, Search, Eye, EyeOff, Copy, Scissors, Clipboard,
    Trash2, Plus, FolderPlus, Edit3, ArrowUp, HardDrive, Star,
    Download, Image, FileText, Film, Music, Archive, Code,
    MoreHorizontal, X, Check
} from 'lucide-react';

interface FileEntry {
    name: string;
    path: string;
    isDir: boolean;
    size: number;
    modified: string;
    extension: string;
}

interface ClipboardItem {
    paths: string[];
    mode: 'copy' | 'cut';
}

const ICON_MAP: Record<string, React.ComponentType<any>> = {
    // Images
    png: Image, jpg: Image, jpeg: Image, gif: Image, webp: Image, svg: Image, ico: Image,
    // Video
    mp4: Film, mkv: Film, avi: Film, mov: Film, webm: Film,
    // Audio
    mp3: Music, wav: Music, flac: Music, ogg: Music, m4a: Music,
    // Docs
    txt: FileText, md: FileText, pdf: FileText, doc: FileText, docx: FileText,
    // Code
    ts: Code, tsx: Code, js: Code, jsx: Code, rs: Code, py: Code, sh: Code, json: Code, toml: Code, yaml: Code, yml: Code, css: Code, html: Code, cr: Code,
    // Archives
    zip: Archive, tar: Archive, gz: Archive, '7z': Archive, rar: Archive,
};

function getFileIcon(entry: FileEntry): React.ComponentType<any> {
    if (entry.isDir) return Folder;
    return ICON_MAP[entry.extension?.toLowerCase()] || File;
}

function formatSize(bytes: number): string {
    if (bytes === 0) return '—';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
    return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

const BOOKMARKS = [
    { label: 'Home',      path: '',       icon: Home },
    { label: 'Downloads', path: '/Downloads', icon: Download },
    { label: 'Documents', path: '/Documents', icon: FileText },
    { label: 'Pictures',  path: '/Pictures',  icon: Image },
    { label: 'Music',     path: '/Music',     icon: Music },
    { label: 'Videos',    path: '/Videos',    icon: Film },
];

const ExplorerApp: React.FC<AppProps> = () => {
    const [currentPath, setCurrentPath] = useState('');
    const [entries, setEntries] = useState<FileEntry[]>([]);
    const [selected, setSelected] = useState<Set<string>>(new Set());
    const [clipboard, setClipboard] = useState<ClipboardItem | null>(null);
    const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
    const [showHidden, setShowHidden] = useState(false);
    const [searchQuery, setSearchQuery] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [history, setHistory] = useState<string[]>([]);
    const [historyIndex, setHistoryIndex] = useState(-1);
    const [renaming, setRenaming] = useState<string | null>(null);
    const [renameValue, setRenameValue] = useState('');
    const [contextMenu, setContextMenu] = useState<{ x: number; y: number; path: string; isDir: boolean } | null>(null);
    const [homeDir, setHomeDir] = useState('');
    const renameInputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        // Get home dir
        SystemBridge.executeCommand('echo $HOME').then(result => {
            const home = (typeof result === 'string' ? result : result.stdout).trim();
            setHomeDir(home);
            navigate(home);
        });
    }, []);

    const navigate = useCallback(async (path: string, addToHistory = true) => {
        setLoading(true);
        setError(null);
        setSelected(new Set());
        setSearchQuery('');
        try {
            const raw = await SystemBridge.executeCommand(
                `ls -la --time-style="+%Y-%m-%d %H:%M" "${path}" 2>&1 || echo "ERROR"`
            );
            const result = typeof raw === 'string' ? raw : (raw.stdout || raw.stderr || '');

            if (result.includes('ERROR') && !result.trim().startsWith('total')) {
                setError(`Cannot access: ${path}`);
                setLoading(false);
                return;
            }

            const lines = result.split('\n').filter((l: string) => l.trim() && !l.startsWith('total'));
            const parsed: FileEntry[] = [];

            for (const line of lines) {
                const parts = line.trim().split(/\s+/);
                if (parts.length < 9) continue;
                const perms = parts[0];
                const size = parseInt(parts[4]) || 0;
                const name = parts.slice(8).join(' ');
                if (name === '.' || name === '..') continue;
                const isDir = perms.startsWith('d');
                const isLink = perms.startsWith('l');
                const ext = name.includes('.') ? name.split('.').pop() || '' : '';
                const entryPath = `${path}/${name}`.replace('//', '/');
                parsed.push({ name, path: entryPath, isDir: isDir || (isLink && false), size, modified: `${parts[6]} ${parts[7]}`, extension: ext });
            }

            // Sort: dirs first, then files, both alphabetically
            parsed.sort((a, b) => {
                if (a.isDir && !b.isDir) return -1;
                if (!a.isDir && b.isDir) return 1;
                return a.name.localeCompare(b.name);
            });

            setEntries(parsed);
            setCurrentPath(path);

            if (addToHistory) {
                const newHistory = [...history.slice(0, historyIndex + 1), path];
                setHistory(newHistory);
                setHistoryIndex(newHistory.length - 1);
            }
        } catch (e) {
            setError('Failed to read directory');
        } finally {
            setLoading(false);
        }
    }, [history, historyIndex]);

    const goBack = () => {
        if (historyIndex > 0) {
            const path = history[historyIndex - 1];
            setHistoryIndex(h => h - 1);
            navigate(path, false);
        }
    };

    const goForward = () => {
        if (historyIndex < history.length - 1) {
            const path = history[historyIndex + 1];
            setHistoryIndex(h => h + 1);
            navigate(path, false);
        }
    };

    const goUp = () => {
        const parent = currentPath.split('/').slice(0, -1).join('/') || '/';
        navigate(parent);
    };

    const handleOpen = (entry: FileEntry) => {
        if (entry.isDir) {
            navigate(entry.path);
        } else {
            SystemBridge.executeCommand(`xdg-open "${entry.path}" &`).catch(() => {});
        }
    };

    const handleSelect = (e: React.MouseEvent, path: string) => {
        if (e.ctrlKey || e.metaKey) {
            setSelected(prev => {
                const next = new Set(prev);
                next.has(path) ? next.delete(path) : next.add(path);
                return next;
            });
        } else if (e.shiftKey) {
            const idx = filteredEntries.findIndex(f => f.path === path);
            const lastSelected = filteredEntries.findIndex(f => selected.has(f.path));
            if (lastSelected >= 0) {
                const [from, to] = [Math.min(idx, lastSelected), Math.max(idx, lastSelected)];
                setSelected(new Set(filteredEntries.slice(from, to + 1).map(f => f.path)));
            }
        } else {
            setSelected(new Set([path]));
        }
    };

    const handleCopy = (paths: string[]) => setClipboard({ paths, mode: 'copy' });
    const handleCut = (paths: string[]) => setClipboard({ paths, mode: 'cut' });

    const handlePaste = async () => {
        if (!clipboard) return;
        const cmd = clipboard.mode === 'copy'
            ? `cp -r ${clipboard.paths.map(p => `"${p}"`).join(' ')} "${currentPath}/"`
            : `mv ${clipboard.paths.map(p => `"${p}"`).join(' ')} "${currentPath}/"`;
        await SystemBridge.executeCommand(cmd).catch(() => {});
        if (clipboard.mode === 'cut') setClipboard(null);
        navigate(currentPath, false);
    };

    const handleDelete = async (paths: string[]) => {
        const names = paths.map(p => p.split('/').pop()).join(', ');
        if (!window.confirm(`Delete ${names}?`)) return;
        await SystemBridge.executeCommand(`rm -rf ${paths.map(p => `"${p}"`).join(' ')}`);
        setSelected(new Set());
        navigate(currentPath, false);
    };

    const handleNewFolder = async () => {
        const name = window.prompt('Folder name:');
        if (!name) return;
        await SystemBridge.executeCommand(`mkdir -p "${currentPath}/${name}"`);
        navigate(currentPath, false);
    };

    const handleNewFile = async () => {
        const name = window.prompt('File name:');
        if (!name) return;
        await SystemBridge.executeCommand(`touch "${currentPath}/${name}"`);
        navigate(currentPath, false);
    };

    const startRename = (entry: FileEntry) => {
        setRenaming(entry.path);
        setRenameValue(entry.name);
        setTimeout(() => renameInputRef.current?.select(), 50);
    };

    const finishRename = async () => {
        if (!renaming || !renameValue.trim()) { setRenaming(null); return; }
        const dir = renaming.split('/').slice(0, -1).join('/');
        const newPath = `${dir}/${renameValue.trim()}`;
        if (newPath !== renaming) {
            await SystemBridge.executeCommand(`mv "${renaming}" "${newPath}"`);
            navigate(currentPath, false);
        }
        setRenaming(null);
    };

    const handleContextMenu = (e: React.MouseEvent, entry: FileEntry) => {
        e.preventDefault();
        setContextMenu({ x: e.clientX, y: e.clientY, path: entry.path, isDir: entry.isDir });
        if (!selected.has(entry.path)) setSelected(new Set([entry.path]));
    };

    const filteredEntries = entries.filter(e => {
        if (!showHidden && e.name.startsWith('.')) return false;
        if (searchQuery && !e.name.toLowerCase().includes(searchQuery.toLowerCase())) return false;
        return true;
    });

    const selectedPaths = Array.from(selected);

    const pathParts = currentPath.split('/').filter(Boolean);

    return (
        <div
            className="flex flex-col h-full bg-slate-900 text-white overflow-hidden"
            onClick={() => setContextMenu(null)}
        >
            {/* Toolbar */}
            <div className="shrink-0 flex items-center gap-1 px-3 py-2 bg-slate-800 border-b border-white/5">
                {/* Nav buttons */}
                <button onClick={goBack} disabled={historyIndex <= 0} className="p-1.5 hover:bg-white/10 rounded-lg disabled:opacity-30 transition-colors">
                    <ChevronLeft size={16} />
                </button>
                <button onClick={goForward} disabled={historyIndex >= history.length - 1} className="p-1.5 hover:bg-white/10 rounded-lg disabled:opacity-30 transition-colors">
                    <ChevronRight size={16} />
                </button>
                <button onClick={goUp} disabled={currentPath === '/'} className="p-1.5 hover:bg-white/10 rounded-lg disabled:opacity-30 transition-colors">
                    <ArrowUp size={16} />
                </button>
                <button onClick={() => navigate(homeDir)} className="p-1.5 hover:bg-white/10 rounded-lg transition-colors">
                    <Home size={16} />
                </button>
                <button onClick={() => navigate(currentPath, false)} className="p-1.5 hover:bg-white/10 rounded-lg transition-colors">
                    <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
                </button>

                {/* Breadcrumb */}
                <div className="flex-1 flex items-center gap-0.5 bg-slate-900/50 rounded-lg px-2 py-1 mx-1 overflow-x-auto scrollbar-hide text-sm">
                    <button onClick={() => navigate('/')} className="hover:text-blue-400 text-slate-400 shrink-0">/</button>
                    {pathParts.map((part, i) => {
                        const path = '/' + pathParts.slice(0, i + 1).join('/');
                        return (
                            <React.Fragment key={i}>
                                <ChevronRight size={12} className="text-slate-600 shrink-0" />
                                <button onClick={() => navigate(path)} className="hover:text-blue-400 whitespace-nowrap shrink-0 transition-colors">
                                    {part}
                                </button>
                            </React.Fragment>
                        );
                    })}
                </div>

                {/* Search */}
                <div className="relative">
                    <Search size={13} className="absolute left-2 top-1/2 -translate-y-1/2 text-slate-500" />
                    <input
                        value={searchQuery}
                        onChange={e => setSearchQuery(e.target.value)}
                        placeholder="Search..."
                        className="bg-slate-900/50 border border-white/10 rounded-lg pl-7 pr-3 py-1 text-sm w-40 focus:outline-none focus:border-blue-500/50"
                    />
                    {searchQuery && (
                        <button onClick={() => setSearchQuery('')} className="absolute right-2 top-1/2 -translate-y-1/2">
                            <X size={12} className="text-slate-400" />
                        </button>
                    )}
                </div>

                {/* View toggles */}
                <button onClick={() => setShowHidden(s => !s)} className={`p-1.5 rounded-lg transition-colors ${showHidden ? 'text-blue-400 bg-blue-500/10' : 'hover:bg-white/10 text-slate-400'}`} title="Show hidden">
                    {showHidden ? <Eye size={15} /> : <EyeOff size={15} />}
                </button>
                <button onClick={() => setViewMode('grid')} className={`p-1.5 rounded-lg transition-colors ${viewMode === 'grid' ? 'text-blue-400 bg-blue-500/10' : 'hover:bg-white/10 text-slate-400'}`}>
                    <Grid size={15} />
                </button>
                <button onClick={() => setViewMode('list')} className={`p-1.5 rounded-lg transition-colors ${viewMode === 'list' ? 'text-blue-400 bg-blue-500/10' : 'hover:bg-white/10 text-slate-400'}`}>
                    <List size={15} />
                </button>

                {/* Actions */}
                <div className="flex gap-0.5 ml-1 border-l border-white/10 pl-1">
                    <button onClick={handleNewFolder} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400" title="New folder">
                        <FolderPlus size={15} />
                    </button>
                    <button onClick={handleNewFile} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400" title="New file">
                        <Plus size={15} />
                    </button>
                    {clipboard && (
                        <button onClick={handlePaste} className="p-1.5 hover:bg-white/10 rounded-lg text-green-400" title="Paste">
                            <Clipboard size={15} />
                        </button>
                    )}
                </div>
            </div>

            <div className="flex flex-1 overflow-hidden">
                {/* Sidebar */}
                <div className="w-40 shrink-0 bg-slate-800/50 border-r border-white/5 overflow-y-auto py-2">
                    <div className="px-3 py-1 text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Bookmarks</div>
                    {BOOKMARKS.map(bm => {
                        const fullPath = bm.path ? homeDir + bm.path : homeDir;
                        const Icon = bm.icon;
                        return (
                            <button
                                key={bm.label}
                                onClick={() => navigate(fullPath)}
                                className={`w-full flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-white/10 transition-colors text-left ${currentPath === fullPath ? 'text-blue-400 bg-blue-500/10' : 'text-slate-300'}`}
                            >
                                <Icon size={14} className="shrink-0" />
                                {bm.label}
                            </button>
                        );
                    })}
                    <div className="px-3 py-1 text-[10px] font-semibold text-slate-500 uppercase tracking-wider mt-3">Devices</div>
                    {['/'].map(path => (
                        <button
                            key={path}
                            onClick={() => navigate(path)}
                            className="w-full flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-white/10 transition-colors text-left text-slate-300"
                        >
                            <HardDrive size={14} className="shrink-0" />
                            Root (/)
                        </button>
                    ))}
                </div>

                {/* Main content */}
                <div
                    className="flex-1 overflow-y-auto p-3"
                    onClick={() => setSelected(new Set())}
                >
                    {error ? (
                        <div className="flex flex-col items-center justify-center h-full text-red-400">
                            <X size={32} className="mb-2" />
                            <p className="text-sm">{error}</p>
                        </div>
                    ) : loading ? (
                        <div className="flex items-center justify-center h-full">
                            <RefreshCw size={24} className="animate-spin text-blue-400" />
                        </div>
                    ) : filteredEntries.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-full text-slate-500">
                            <Folder size={48} className="mb-3 opacity-30" />
                            <p className="text-sm">{searchQuery ? 'No matches' : 'Empty folder'}</p>
                        </div>
                    ) : viewMode === 'grid' ? (
                        <div className="grid grid-cols-[repeat(auto-fill,minmax(90px,1fr))] gap-2">
                            {filteredEntries.map(entry => {
                                const Icon = getFileIcon(entry);
                                const isSelected = selected.has(entry.path);
                                const isRenaming = renaming === entry.path;
                                return (
                                    <div
                                        key={entry.path}
                                        onClick={e => { e.stopPropagation(); handleSelect(e, entry.path); }}
                                        onDoubleClick={() => isRenaming ? undefined : handleOpen(entry)}
                                        onContextMenu={e => handleContextMenu(e, entry)}
                                        className={`flex flex-col items-center gap-1 p-2 rounded-xl cursor-pointer transition-all select-none ${isSelected ? 'bg-blue-600/30 ring-1 ring-blue-500/50' : 'hover:bg-white/5'}`}
                                    >
                                        <Icon size={36} className={`shrink-0 ${entry.isDir ? 'text-blue-400' : 'text-slate-400'}`} />
                                        {isRenaming ? (
                                            <input
                                                ref={renameInputRef}
                                                value={renameValue}
                                                onChange={e => setRenameValue(e.target.value)}
                                                onBlur={finishRename}
                                                onKeyDown={e => { if (e.key === 'Enter') finishRename(); if (e.key === 'Escape') setRenaming(null); }}
                                                onClick={e => e.stopPropagation()}
                                                className="w-full bg-slate-700 text-white text-xs text-center rounded px-1 focus:outline-none"
                                                autoFocus
                                            />
                                        ) : (
                                            <span className="text-xs text-center break-all line-clamp-2 text-slate-200 w-full">
                                                {entry.name}
                                            </span>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    ) : (
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="text-slate-500 text-xs border-b border-white/5">
                                    <th className="text-left py-1 px-2 font-medium">Name</th>
                                    <th className="text-right py-1 px-2 font-medium w-24">Size</th>
                                    <th className="text-right py-1 px-2 font-medium w-36">Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                {filteredEntries.map(entry => {
                                    const Icon = getFileIcon(entry);
                                    const isSelected = selected.has(entry.path);
                                    const isRenaming = renaming === entry.path;
                                    return (
                                        <tr
                                            key={entry.path}
                                            onClick={e => { e.stopPropagation(); handleSelect(e, entry.path); }}
                                            onDoubleClick={() => handleOpen(entry)}
                                            onContextMenu={e => handleContextMenu(e, entry)}
                                            className={`cursor-pointer transition-colors rounded-lg ${isSelected ? 'bg-blue-600/20' : 'hover:bg-white/5'}`}
                                        >
                                            <td className="py-1 px-2">
                                                <div className="flex items-center gap-2">
                                                    <Icon size={16} className={`shrink-0 ${entry.isDir ? 'text-blue-400' : 'text-slate-400'}`} />
                                                    {isRenaming ? (
                                                        <input
                                                            ref={renameInputRef}
                                                            value={renameValue}
                                                            onChange={e => setRenameValue(e.target.value)}
                                                            onBlur={finishRename}
                                                            onKeyDown={e => { if (e.key === 'Enter') finishRename(); if (e.key === 'Escape') setRenaming(null); }}
                                                            onClick={e => e.stopPropagation()}
                                                            className="bg-slate-700 text-white text-sm rounded px-1 focus:outline-none w-48"
                                                            autoFocus
                                                        />
                                                    ) : (
                                                        <span className="text-slate-200 truncate">{entry.name}</span>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="py-1 px-2 text-right text-slate-500 text-xs">{entry.isDir ? '—' : formatSize(entry.size)}</td>
                                            <td className="py-1 px-2 text-right text-slate-500 text-xs">{entry.modified}</td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    )}
                </div>
            </div>

            {/* Status bar */}
            <div className="shrink-0 flex items-center justify-between px-4 py-1.5 bg-slate-800/50 border-t border-white/5 text-xs text-slate-500">
                <span>{filteredEntries.length} items{selected.size > 0 ? ` · ${selected.size} selected` : ''}</span>
                <div className="flex items-center gap-3">
                    {clipboard && (
                        <span className={`${clipboard.mode === 'cut' ? 'text-orange-400' : 'text-green-400'}`}>
                            {clipboard.paths.length} item(s) ready to {clipboard.mode === 'cut' ? 'move' : 'copy'}
                            <button onClick={() => setClipboard(null)} className="ml-1 hover:text-white"><X size={10} /></button>
                        </span>
                    )}
                    {selectedPaths.length > 0 && (
                        <div className="flex gap-1">
                            <button onClick={() => handleCopy(selectedPaths)} className="hover:text-white p-0.5" title="Copy"><Copy size={12} /></button>
                            <button onClick={() => handleCut(selectedPaths)} className="hover:text-white p-0.5" title="Cut"><Scissors size={12} /></button>
                            <button onClick={() => handleDelete(selectedPaths)} className="hover:text-red-400 p-0.5" title="Delete"><Trash2 size={12} /></button>
                        </div>
                    )}
                </div>
            </div>

            {/* Context menu */}
            {contextMenu && (
                <div
                    className="fixed z-50 bg-slate-800 border border-white/10 rounded-xl shadow-2xl py-1 min-w-44"
                    style={{ left: contextMenu.x, top: contextMenu.y }}
                    onClick={e => e.stopPropagation()}
                >
                    {[
                        { label: 'Open', icon: contextMenu.isDir ? Folder : File, action: () => { const e = filteredEntries.find(f => f.path === contextMenu.path); if (e) handleOpen(e); } },
                        { label: 'Rename', icon: Edit3, action: () => { const e = filteredEntries.find(f => f.path === contextMenu.path); if (e) startRename(e); } },
                        null,
                        { label: 'Copy', icon: Copy, action: () => handleCopy(selectedPaths.length > 0 ? selectedPaths : [contextMenu.path]) },
                        { label: 'Cut', icon: Scissors, action: () => handleCut(selectedPaths.length > 0 ? selectedPaths : [contextMenu.path]) },
                        clipboard ? { label: 'Paste', icon: Clipboard, action: handlePaste } : null,
                        null,
                        { label: 'Delete', icon: Trash2, action: () => handleDelete(selectedPaths.length > 0 ? selectedPaths : [contextMenu.path]), danger: true },
                    ].map((item, i) => {
                        if (!item) return <div key={i} className="border-t border-white/5 my-1" />;
                        const Icon = item.icon;
                        return (
                            <button
                                key={item.label}
                                onClick={() => { item.action(); setContextMenu(null); }}
                                className={`w-full flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-white/10 transition-colors text-left ${(item as any).danger ? 'text-red-400' : 'text-slate-200'}`}
                            >
                                <Icon size={14} className="shrink-0" />
                                {item.label}
                            </button>
                        );
                    })}
                </div>
            )}
        </div>
    );
};

export default ExplorerApp;
